# Schema for the configuration files of the Chalk Module module.
chalk_module.settings:
  type: config_object
  label: 'Chalk Module settings'
  mapping:
    example:
      type: string
      label: 'Example'
