exports.generateColorShades = require('./scripts/generateColorShades')
exports.generateTokens = require('./scripts/generateTokens')
exports.generateColorContrasts = require('./scripts/generateColorContrasts')
exports.generateColorSuggestions = require('./scripts/generateColorSuggestions')
exports.getConfigTokens = require('./scripts/getConfigTokens')
