<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_menu_local_tasks_alter().
 */
function chalk_module_menu_local_tasks_alter(&$local_tasks, $data, $route_name) {
  $menu_name = isset($data['route']) ? $data['route']->getOption('_menu_name') : '';

  if ($menu_name == 'admin' && $route_name == 'system.admin') {
    $data['tabs'][0]['chalk_theme_settings.admin'] = [
      '#theme' => 'menu_local_task',
      '#link' => [
        'title' => t('Chalk Theme Settings'),
        'route_name' => 'chalk_theme_settings.admin',
      ],
    ];
  }
}
